services:
  dev-misc:
    container_name: dev-misc
    stdin_open: true
    tty: true
    # environment:
    #   PORT: 8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8010:8000
      - 5679:5678
    #restart: always
    volumes:
      - "misc-vol:/code"
volumes:
  misc-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/franco/Documents/dev