FROM continuumio/miniconda3:23.9.0-0

LABEL maintainer="dev@coloccini.com.ar"

# Configure Python to not buffer "stdout" or create .pyc files
ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /code

COPY ./requirements*.txt ./
RUN pip install --no-cache-dir -r ./requirements-dev.txt
 
EXPOSE 8000

WORKDIR /code/

# CMD ["python", "main.py"]

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
